import type { ChatGateway } from '../domain/chatGateway'
import { ChatUnavailableError, ReplyInterruptedError } from '../domain/errors'
import type { Message, ReplyChunk } from '../domain/message'
import { EMPTY_SHA256, readJson, sha256Hex, toRejection } from './chatHttp'

/**
 * The reply, obtained by asking for it repeatedly instead of holding a socket.
 *
 * Satisfies the same {@link ChatGateway} port as the streamed gateway, which is
 * why nothing above this file changes: `useChat` still consumes an async
 * iterable of chunks and still cancels with an `AbortSignal`. What it buys is
 * durability — the reply is generated by a process that does not care whether
 * this page is still listening — and the ability to stop that process, which a
 * streamed response cannot do.
 *
 * The shape of the exchange:
 *
 *   POST   /api/chat/jobs                    → 202 {job_id}
 *   GET    /api/chat/jobs/{id}/segments/{n}  → {status, segments, cursor, …}
 *   DELETE /api/chat/jobs/{id}               → 204
 *
 * The cursor is **the number of segments already seen**, and it is a path
 * segment rather than a query string on purpose: the CDN's cache policy excludes
 * query strings from the cache key, so a cursor there would be correct only for
 * as long as nobody raises a TTL.
 */

/** Same relative path in dev (via the Vite proxy) and in production. */
export const DEFAULT_JOBS_ENDPOINT = '/api/chat/jobs'

const HTTP_NOT_FOUND = 404
const HTTP_SERVER_ERROR = 500

/** Statuses that end the exchange. Mirrors `JobStatus.is_terminal`. */
const DONE = 'done'
const CANCELLED = 'cancelled'
const TERMINAL: ReadonlySet<string> = new Set([DONE, 'failed', CANCELLED])

/**
 * Bounds on the server's suggested poll interval.
 *
 * The interval is the server's to choose — it can be retuned without rebuilding
 * this bundle — but not without limit: zero would spin, and a large value would
 * look like a hang. Clamping keeps a configuration mistake from becoming a
 * client-side defect.
 */
const MIN_POLL_MS = 100
const MAX_POLL_MS = 5_000
const FALLBACK_POLL_MS = 400

/**
 * How long to keep asking before giving up.
 *
 * Sits **above** the server's own deadline, currently 660 s, and that ordering
 * is the whole design: a job the server has given up on reports itself as
 * `failed` with a reason worth showing, so the server should always be the one
 * to speak first. This bound exists only for the case where the server never
 * reaches a terminal status at all, which is a defect rather than a state.
 */
const DEFAULT_MAX_WAIT_MS = 720_000

/**
 * How many consecutive read failures to ride out before reporting one.
 *
 * A dropped poll is not a dropped reply. The work continues on the server
 * whatever happens to this page, so treating one failed `GET` as the end of the
 * reply would throw away the durability that is the reason for this transport.
 */
const MAX_READ_FAILURES = 3

interface JobsChatGatewayOptions {
  readonly endpoint?: string
  readonly maxWaitMs?: number
}

/** One poll's answer, in this codebase's naming rather than the wire's. */
interface Progress {
  readonly status: string
  readonly segments: readonly string[]
  readonly cursor: number
  readonly nextPollMs: number
  readonly error: string | null
}

/**
 * A read that failed in a way worth retrying: a network blip or a 5xx.
 *
 * Private to this module and never allowed to escape — the port permits three
 * error types and this is not one of them, so exhausting the retries converts it.
 */
class TransientReadError extends Error {}

export class JobsChatGateway implements ChatGateway {
  /** Public so the composition root can label the wire readout with the truth. */
  readonly endpoint: string

  private readonly maxWaitMs: number

  constructor(options: JobsChatGatewayOptions = {}) {
    this.endpoint = options.endpoint ?? DEFAULT_JOBS_ENDPOINT
    this.maxWaitMs = options.maxWaitMs ?? DEFAULT_MAX_WAIT_MS
  }

  async *send(
    message: string,
    history: readonly Message[],
    signal?: AbortSignal,
  ): AsyncIterable<ReplyChunk> {
    const jobId = await this.submit(message, history, signal)

    const stopWatchingForUnload = this.cancelOnUnload(jobId)
    const startedAt = Date.now()
    let cursor = 0
    let failures = 0
    let settled = false

    try {
      for (;;) {
        let progress: Progress
        try {
          progress = await this.read(jobId, cursor, signal)
          failures = 0
        } catch (error) {
          if (!(error instanceof TransientReadError)) throw error
          failures += 1
          if (failures >= MAX_READ_FAILURES) {
            throw new ChatUnavailableError('The assistant stopped answering.', {
              cause: error,
            })
          }
          await sleep(FALLBACK_POLL_MS, signal)
          continue
        }

        for (const text of progress.segments) {
          // `wire.frames` therefore counts segments, not tokens — each one is a
          // batch of the reply as it was flushed, so the readout climbs in
          // steps rather than smoothly.
          if (text !== '') yield { text }
        }

        // Never move backwards. A stale read can be shorter than the position
        // already reached, in which case it carries no segments and no news.
        cursor = Math.max(cursor, progress.cursor)

        if (TERMINAL.has(progress.status)) {
          // Terminal is sticky by construction: the loop ends here, so no later
          // answer can un-finish a reply that has finished.
          settled = true
          if (progress.status === DONE) return

          if (progress.status === CANCELLED && signal?.aborted === true) {
            // Our own doing. Whatever arrived is the reply, and the caller
            // already knows why it stopped.
            return
          }

          throw new ReplyInterruptedError(
            progress.error ?? 'The reply stopped before it finished.',
          )
        }

        if (Date.now() - startedAt > this.maxWaitMs) {
          throw new ReplyInterruptedError('The reply never finished.')
        }

        await sleep(progress.nextPollMs, signal)
      }
    } finally {
      stopWatchingForUnload()
      // Reached on an abort, on a thrown error, and when the consumer abandons
      // the loop — the last of which is the port's fifth obligation and, here,
      // also the difference between paying for an abandoned reply and not.
      if (!settled) this.cancel(jobId)
    }
  }

  private async submit(
    message: string,
    history: readonly Message[],
    signal?: AbortSignal,
  ): Promise<string> {
    // Rebuilt rather than passed through, so nothing the UI happens to keep on
    // an entry can leak into the request body. Built once, because the payload
    // hash has to be taken over the exact bytes that get sent.
    const body = JSON.stringify({
      message,
      history: history.map(({ role, content }) => ({ role, content })),
    })

    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
      Accept: 'application/json',
    }

    const payloadHash = await sha256Hex(body)
    if (payloadHash !== null) {
      headers['x-amz-content-sha256'] = payloadHash
    }

    let response: Response
    try {
      response = await fetch(this.endpoint, {
        method: 'POST',
        headers,
        body,
        cache: 'no-store',
        signal: signal ?? null,
      })
    } catch (cause) {
      if (signal?.aborted === true) throw cause
      throw new ChatUnavailableError('The assistant could not be reached.', {
        cause,
      })
    }

    // A 404 here means the job routes are not mounted, so this deployment
    // cannot serve this transport at all. `toRejection` reports the status
    // rather than guessing, which is the honest answer for a request that
    // should never have been sent — the health probe exists to prevent it.
    if (!response.ok) throw await toRejection(response)

    const created = await readJson(response)
    const jobId = (created as { job_id?: unknown }).job_id

    if (typeof jobId !== 'string' || jobId === '') {
      throw new ChatUnavailableError('The assistant accepted the message but named no job.')
    }
    return jobId
  }

  private async read(
    jobId: string,
    cursor: number,
    signal?: AbortSignal,
  ): Promise<Progress> {
    const url = `${this.endpoint}/${encodeURIComponent(jobId)}/segments/${String(cursor)}`

    let response: Response
    try {
      response = await fetch(url, {
        method: 'GET',
        headers: { 'x-amz-content-sha256': EMPTY_SHA256 },
        cache: 'no-store',
        signal: signal ?? null,
      })
    } catch (cause) {
      if (signal?.aborted === true) throw cause
      throw new TransientReadError('The poll did not complete.', { cause })
    }

    if (response.status === HTTP_NOT_FOUND) {
      // The record is gone: expired, or removed. Retrying cannot bring it back,
      // and whatever text already arrived is all there will be.
      throw new ReplyInterruptedError('The reply is no longer available.')
    }

    if (response.status >= HTTP_SERVER_ERROR) {
      throw new TransientReadError(`The poll answered with ${String(response.status)}.`)
    }

    if (!response.ok) throw await toRejection(response)

    return toProgress(await readJson(response))
  }

  /**
   * Stop the work, without waiting to hear that it stopped.
   *
   * Not given the caller's `AbortSignal`, deliberately: this is sent *because*
   * the signal fired, so passing it would cancel the cancellation. `keepalive`
   * lets the request outlive the page, which is what makes the unload case
   * below work at all.
   */
  private cancel(jobId: string): void {
    void fetch(`${this.endpoint}/${encodeURIComponent(jobId)}`, {
      method: 'DELETE',
      headers: { 'x-amz-content-sha256': EMPTY_SHA256 },
      cache: 'no-store',
      keepalive: true,
    }).catch(() => undefined)
  }

  /**
   * Cancel the job if the page goes away mid-reply.
   *
   * **The Stop button is not the dominant abandonment mode.** `useChat` aborts
   * on unmount, but browsers do not unmount React when a tab is closed or
   * navigated away from — that path fires nothing at all, and without this the
   * worker would generate a reply for a page that no longer exists and bill for
   * every second of it.
   *
   * `pagehide` rather than `unload`, which is unreliable and blocks the back /
   * forward cache. `persisted` is respected: a page entering that cache may
   * well come back, and cancelling a reply somebody could still return to would
   * trade a small cost for a broken answer. The residual risk is a cached page
   * that is silently evicted, which leaks at most one reply's work and is
   * bounded by the worker's own timeout.
   *
   * `navigator.sendBeacon` cannot be used: it only issues POSTs, and this is a
   * DELETE.
   */
  private cancelOnUnload(jobId: string): () => void {
    const onPageHide = (event: PageTransitionEvent): void => {
      if (event.persisted) return
      this.cancel(jobId)
    }

    window.addEventListener('pagehide', onPageHide)
    return () => {
      window.removeEventListener('pagehide', onPageHide)
    }
  }
}

/**
 * Wait, unless the caller stops us first.
 *
 * A plain `setTimeout` would leave Stop feeling broken for up to a whole poll
 * interval — and, worse, would keep the worker generating for that long after
 * the person asked it not to.
 */
function sleep(ms: number, signal?: AbortSignal): Promise<void> {
  return new Promise<void>((resolve, reject) => {
    if (signal?.aborted === true) {
      reject(signal.reason)
      return
    }

    const onAbort = (): void => {
      clearTimeout(timer)
      reject(signal?.reason)
    }

    const timer = setTimeout(() => {
      signal?.removeEventListener('abort', onAbort)
      resolve()
    }, ms)

    signal?.addEventListener('abort', onAbort, { once: true })
  })
}

/** Read one poll's answer, or say that it could not be read. */
function toProgress(body: unknown): Progress {
  if (typeof body !== 'object' || body === null) {
    throw new ChatUnavailableError('The assistant sent an unreadable reply.')
  }

  const raw = body as {
    status?: unknown
    segments?: unknown
    cursor?: unknown
    next_poll_ms?: unknown
    error?: unknown
  }

  // A segment that is not a string would silently drop text if it were merely
  // filtered out, so the whole answer is refused instead.
  if (
    typeof raw.status !== 'string' ||
    !Array.isArray(raw.segments) ||
    !raw.segments.every((segment) => typeof segment === 'string')
  ) {
    throw new ChatUnavailableError('The assistant sent an unreadable reply.')
  }

  return {
    status: raw.status,
    segments: raw.segments as readonly string[],
    cursor: typeof raw.cursor === 'number' && raw.cursor >= 0 ? raw.cursor : 0,
    nextPollMs: clampPoll(raw.next_poll_ms),
    error: typeof raw.error === 'string' && raw.error !== '' ? raw.error : null,
  }
}

function clampPoll(value: unknown): number {
  const asked =
    typeof value === 'number' && Number.isFinite(value) ? value : FALLBACK_POLL_MS
  return Math.min(Math.max(asked, MIN_POLL_MS), MAX_POLL_MS)
}
